name: reviewdog
on:
  pull_request:
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'

jobs:

  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.38.1

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Optional. Change reporter
        fail_on_error: "true" # Optional. Fail action if errors are found
        filter_mode: "nofilter" # Optional. Check all files, not just the diff
        level: info
        flags: "--module" # Optional. Add custom tflint flags
